//	Altirra - Atari 800/800XL/5200 emulator
//	Copyright (C) 2024 Avery Lee
//	Linux port contributions
//
//	This program is free software; you can redistribute it and/or modify
//	it under the terms of the GNU General Public License as published by
//	the Free Software Foundation; either version 2 of the License, or
//	(at your option) any later version.

#pragma once

#include <wx/defs.h>

// Menu item IDs for the wxWidgets menu bar.
// Groups are spaced to allow future additions within each category.
enum ATMenuId {
	// System menu (1000-1099)
	ID_SYSTEM_WARM_RESET = 1000,
	ID_SYSTEM_COLD_RESET,
	ID_SYSTEM_TOGGLE_BASIC,
	ID_SYSTEM_TOGGLE_PAUSE_INACTIVE,
	ID_SYSTEM_TOGGLE_REWIND,
	ID_SYSTEM_REWIND,
	ID_SYSTEM_SAVE_SETTINGS,
	ID_SYSTEM_QUIT,

	// Hardware mode submenu (1100-1119)
	ID_HW_800 = 1100,
	ID_HW_800XL,
	ID_HW_1200XL,
	ID_HW_130XE,
	ID_HW_XEGS,
	ID_HW_5200,

	// Video standard submenu (1120-1129)
	ID_VIDEOSTD_NTSC = 1120,
	ID_VIDEOSTD_PAL,
	ID_VIDEOSTD_SECAM,
	ID_VIDEOSTD_NTSC50,
	ID_VIDEOSTD_PAL60,

	// Kernel submenu (1130-1149) — dynamic items use ID_KERNEL_USER_FIRST..LAST
	ID_KERNEL_AUTOSELECT = 1130,
	ID_KERNEL_INTERNAL_OSB,
	ID_KERNEL_INTERNAL_XL,
	ID_KERNEL_INTERNAL_5200,
	ID_KERNEL_USER_FIRST = 1135,
	ID_KERNEL_USER_LAST  = 1149,

	// Console switches (1150-1159)
	ID_CONSOLE_OPTION = 1150,
	ID_CONSOLE_SELECT,
	ID_CONSOLE_START,
	ID_CONSOLE_RELEASE_ALL,

	// Memory submenu (1160-1179)
	ID_MEMORY_FIRST = 1160,
	ID_MEMORY_LAST  = 1179,

	// Device Buttons submenu (1180-1199)
	ID_DEVBTN_FIRST = 1180,
	ID_DEVBTN_LAST  = 1199,

	// Power-On Delay submenu (1040-1049)
	ID_POWERON_AUTO = 1040,
	ID_POWERON_NONE,
	ID_POWERON_1SEC,
	ID_POWERON_2SEC,
	ID_POWERON_3SEC,

	// System toggles (1050-1059)
	ID_SYSTEM_HOLD_KEYS_FOR_RESET = 1050,
	ID_SYSTEM_AUTO_BOOT_TAPE,
	ID_SYSTEM_CYCLE_QUICK_MAPS,

	// Profiles menu (1060-1079)
	ID_PROFILE_FIRST = 1060,
	ID_PROFILE_LAST  = 1079,

	// File menu (1200-1299)
	ID_FILE_OPEN_IMAGE = 1200,
	ID_FILE_BOOT_IMAGE,
	ID_FILE_QUICK_SAVE_STATE,
	ID_FILE_QUICK_LOAD_STATE,
	ID_FILE_SAVE_STATE,
	ID_FILE_LOAD_STATE,
	ID_FILE_SAVE_SCREENSHOT,
	ID_FILE_SAVE_SCREENSHOT_TRUE_ASPECT,

	// Per-drive disk submenu — D1..D15 (15 drives x 7 actions = 105 IDs)
	// Each drive gets: Mount, NewDisk, Save, SaveAs, ReadOnly, Explore, Unmount
	ID_DISK_DRIVE_FIRST = 1300,
	// ID = ID_DISK_DRIVE_FIRST + drive * 7 + action
	// actions: 0=Mount 1=NewDisk 2=Save 3=SaveAs 4=ReadOnly 5=Explore 6=Unmount
	ID_DISK_DRIVE_LAST  = 1404,  // 1300 + 14*7 + 6

	ID_DISK_UNMOUNT_ALL = 1410,
	ID_DISK_ROTATE_NEXT,
	ID_DISK_ROTATE_PREV,
	ID_DISK_SAVE_ALL_MODIFIED,

	// Cartridge (1380-1399)
	ID_CART_ATTACH = 1380,
	ID_CART_DETACH,
	ID_CART_SAVE,
	ID_CART_ATTACH_SECONDARY,
	ID_CART_DETACH_SECONDARY,

	// Special cartridge submenu (2100-2119)
	ID_SPECIAL_CART_FIRST = 2100,
	ID_SPECIAL_CART_LAST = 2119,

	// Save firmware submenu (2120-2129)
	ID_SAVE_FW_IDE_MAIN = 2120,
	ID_SAVE_FW_IDE_SDX,
	ID_SAVE_FW_U1MB,
	ID_SAVE_FW_RAPIDUS,

	// Edit menu (1420-1439)
	ID_EDIT_PASTE_TEXT = 1420,
	ID_EDIT_COPY_FRAME,

	// Cassette (1400-1419)
	ID_CASSETTE_LOAD = 1400,
	ID_CASSETTE_UNLOAD,

	// View menu (1500-1599)
	ID_VIEW_TOGGLE_FPS = 1500,
	ID_VIEW_TOGGLE_FULLSCREEN,
	ID_VIEW_TOGGLE_STATUSBAR,

	// Display filter submenu (1520-1529)
	ID_FILTER_POINT = 1520,
	ID_FILTER_BILINEAR,
	ID_FILTER_SHARP_BILINEAR,
	ID_FILTER_BICUBIC,
	ID_FILTER_DEFAULT,

	// Stretch mode submenu (1530-1539)
	ID_STRETCH_FIT = 1530,
	ID_STRETCH_ASPECT,
	ID_STRETCH_ASPECT_INT,
	ID_STRETCH_SQUARE,
	ID_STRETCH_SQUARE_INT,

	// Window size submenu (1540-1549)
	ID_WINSIZE_1X = 1540,
	ID_WINSIZE_2X,
	ID_WINSIZE_3X,
	ID_WINSIZE_4X,

	// Enhanced text submenu (1550-1559)
	ID_ENHTEXT_NONE = 1550,
	ID_ENHTEXT_HARDWARE,
	ID_ENHTEXT_SOFTWARE,

	// Overscan mode submenu (1560-1569)
	ID_OVERSCAN_NORMAL = 1560,
	ID_OVERSCAN_EXTENDED,
	ID_OVERSCAN_FULL,
	ID_OVERSCAN_OS_SCREEN,
	ID_OVERSCAN_WIDESCREEN,

	// Vertical override submenu (1570-1579)
	ID_VERT_DEFAULT = 1570,
	ID_VERT_OS_SCREEN,
	ID_VERT_NORMAL,
	ID_VERT_EXTENDED,
	ID_VERT_FULL,

	// Artifacting mode submenu (1580-1589)
	ID_ARTIFACT_NONE = 1580,
	ID_ARTIFACT_NTSC,
	ID_ARTIFACT_PAL,
	ID_ARTIFACT_NTSC_HI,
	ID_ARTIFACT_PAL_HI,
	ID_ARTIFACT_AUTO,
	ID_ARTIFACT_AUTO_HI,

	// View toggles (1590-1599)
	ID_VIEW_COLOR_SETTINGS = 1588,
	ID_VIEW_TOGGLE_VSYNC = 1590,
	ID_VIEW_TOGGLE_FRAME_BLENDING,
	ID_VIEW_TOGGLE_CONFINE_MOUSE,
	ID_VIEW_TOGGLE_AUDIO_MONITOR,
	ID_VIEW_TOGGLE_AUDIO_SCOPE,
	ID_VIEW_TOGGLE_AUTO_HIDE_CURSOR,
	ID_VIEW_VIDEO_SETTINGS,

	// Speed menu (1600-1699)
	ID_SPEED_TOGGLE_PAUSE = 1600,
	ID_SPEED_TOGGLE_TURBO,
	ID_SPEED_TOGGLE_SLOW,
	ID_SPEED_TOGGLE_MUTE,
	ID_SPEED_PAUSE_INACTIVE,
	ID_SPEED_50 = 1610,
	ID_SPEED_100,
	ID_SPEED_200,
	ID_SPEED_400,
	// Speed slider custom IDs (1620-1639)
	ID_SPEED_CUSTOM_FIRST = 1620,
	ID_SPEED_CUSTOM_LAST  = 1639,

	// Debug menu (1700-1799)
	ID_DEBUG_RUN_STOP = 1700,
	ID_DEBUG_STEP_INTO,
	ID_DEBUG_STEP_OVER,
	ID_DEBUG_STEP_OUT,
	ID_DEBUG_TOGGLE_DEBUGGER,
	ID_DEBUG_TOGGLE_BREAK_AT_EXE,
	ID_DEBUG_TOGGLE_AUTO_RELOAD_ROMS,
	ID_DEBUG_LOAD_SYMBOLS,
	ID_DEBUG_UNLOAD_ALL_SYMBOLS,
	ID_DEBUG_AUTO_LOAD_KERNEL_SYMBOLS,
	ID_DEBUG_AUTO_LOAD_SYSTEM_SYMBOLS,
	ID_DEBUG_DEBUG_LINK,

	// Configure dialogs (1750-1799)
	ID_CONFIGURE_SYSTEM = 1750,
	ID_CONFIGURE_CPU,
	ID_CONFIGURE_BOOT,
	ID_CONFIGURE_KEYBOARD,
	ID_CONFIGURE_AUDIO,
	ID_CONFIGURE_VIDEO,

	// Input setup (1760-1769)
	ID_CONFIGURE_INPUT = 1760,
	ID_INPUT_ON_SCREEN_KEYBOARD,

	// Audio monitor (1770-1779)
	ID_TOOLS_AUDIO_MONITOR = 1770,

	// Tools / Manager dialogs (1800-1899)
	ID_TOOLS_OPEN_CONFIG_DIR = 1800,
	ID_TOOLS_OPEN_FIRMWARE_DIR,
	ID_TOOLS_FIRMWARE_MANAGER,
	ID_TOOLS_DEVICE_MANAGER,
	ID_TOOLS_CARTRIDGE_BROWSER,
	ID_TOOLS_CASSETTE_CONTROL,
	ID_TOOLS_TAPE_EDITOR,
	ID_TOOLS_DISK_EXPLORER,
	ID_TOOLS_PROFILE_MANAGER,
	ID_TOOLS_CHEAT_ENGINE,
	ID_TOOLS_COMPAT_BROWSER,
	ID_TOOLS_RECORD_VIDEO,
	ID_TOOLS_RECORD_AUDIO_WAV,
	ID_TOOLS_RECORD_AUDIO_PCM,
	ID_TOOLS_RECORD_SAP,
	ID_TOOLS_RECORD_VGM,
	ID_TOOLS_STOP_RECORDING,
	ID_TOOLS_EXPORT_ROM_SET,
	ID_TOOLS_CONVERT_SAP_TO_EXE,
	ID_TOOLS_ANALYZE_TAPE_DECODING,
	ID_TOOLS_VIDEO_PAUSE_RESUME,

	// Tools extra (1860-1869)
	ID_TOOLS_ADVANCED_CONFIG = 1860,

	// Help menu (1900-1999)
	ID_HELP_KEYBOARD_SHORTCUTS = 1900,
	ID_HELP_CHANGELOG,
	ID_HELP_HOME_PAGE,
	ID_HELP_CHECK_FOR_UPDATES,
	ID_HELP_ABOUT,

	// MRU / Recent Files (1950-1969)
	ID_MRU_FILE_0 = 1950,
	ID_MRU_FILE_1,
	ID_MRU_FILE_2,
	ID_MRU_FILE_3,
	ID_MRU_FILE_4,
	ID_MRU_FILE_5,
	ID_MRU_FILE_6,
	ID_MRU_FILE_7,
	ID_MRU_FILE_8,
	ID_MRU_FILE_9,
	ID_MRU_CLEAR,

	// Internal (2000+)
	ID_GAMEPAD_TIMER_ID = 2000,
};
