//	Altirra - Atari 800/800XL/5200 emulator
//	Copyright (C) 2024 Avery Lee
//	Linux port contributions
//
//	This program is free software; you can redistribute it and/or modify
//	it under the terms of the GNU General Public License as published by
//	the Free Software Foundation; either version 2 of the License, or
//	(at your option) any later version.

#pragma once

#include <wx/defs.h>

// Menu item IDs for the wxWidgets menu bar.
// Groups are spaced to allow future additions within each category.
enum ATMenuId {
	// System menu (1000-1099)
	ID_SYSTEM_WARM_RESET = 1000,
	ID_SYSTEM_COLD_RESET,
	ID_SYSTEM_TOGGLE_BASIC,
	ID_SYSTEM_TOGGLE_PAUSE_INACTIVE,
	ID_SYSTEM_TOGGLE_REWIND,
	ID_SYSTEM_REWIND,
	ID_SYSTEM_SAVE_SETTINGS,
	ID_SYSTEM_QUIT,

	// Hardware mode submenu (1100-1119)
	ID_HW_800 = 1100,
	ID_HW_800XL,
	ID_HW_1200XL,
	ID_HW_130XE,
	ID_HW_XEGS,
	ID_HW_5200,

	// Video standard submenu (1120-1129)
	ID_VIDEOSTD_NTSC = 1120,
	ID_VIDEOSTD_PAL,
	ID_VIDEOSTD_SECAM,
	ID_VIDEOSTD_NTSC50,
	ID_VIDEOSTD_PAL60,

	// Console switches (1130-1139)
	ID_CONSOLE_OPTION = 1130,
	ID_CONSOLE_SELECT,
	ID_CONSOLE_START,
	ID_CONSOLE_RELEASE_ALL,

	// File menu (1200-1299)
	ID_FILE_OPEN_IMAGE = 1200,
	ID_FILE_BOOT_IMAGE,
	ID_FILE_QUICK_SAVE_STATE,
	ID_FILE_QUICK_LOAD_STATE,
	ID_FILE_SAVE_STATE,
	ID_FILE_LOAD_STATE,
	ID_FILE_SAVE_SCREENSHOT,

	// Disk submenu (1300-1379)
	ID_DISK_MOUNT_D1 = 1300,
	ID_DISK_MOUNT_D2,
	ID_DISK_MOUNT_D3,
	ID_DISK_MOUNT_D4,
	ID_DISK_UNMOUNT_D1 = 1320,
	ID_DISK_UNMOUNT_D2,
	ID_DISK_UNMOUNT_D3,
	ID_DISK_UNMOUNT_D4,
	ID_DISK_UNMOUNT_ALL = 1340,
	ID_DISK_ROTATE_NEXT,
	ID_DISK_ROTATE_PREV,

	// Cartridge (1380-1399)
	ID_CART_ATTACH = 1380,
	ID_CART_DETACH,

	// Cassette (1400-1419)
	ID_CASSETTE_LOAD = 1400,
	ID_CASSETTE_UNLOAD,

	// View menu (1500-1599)
	ID_VIEW_TOGGLE_FPS = 1500,
	ID_VIEW_TOGGLE_FULLSCREEN,
	ID_VIEW_TOGGLE_STATUSBAR,

	// Display filter submenu (1520-1529)
	ID_FILTER_POINT = 1520,
	ID_FILTER_BILINEAR,
	ID_FILTER_SHARP_BILINEAR,
	ID_FILTER_BICUBIC,
	ID_FILTER_DEFAULT,

	// Stretch mode submenu (1530-1539)
	ID_STRETCH_FIT = 1530,
	ID_STRETCH_ASPECT,
	ID_STRETCH_ASPECT_INT,
	ID_STRETCH_SQUARE,
	ID_STRETCH_SQUARE_INT,

	// Window size submenu (1540-1549)
	ID_WINSIZE_1X = 1540,
	ID_WINSIZE_2X,
	ID_WINSIZE_3X,
	ID_WINSIZE_4X,

	// Enhanced text submenu (1550-1559)
	ID_ENHTEXT_NONE = 1550,
	ID_ENHTEXT_HARDWARE,
	ID_ENHTEXT_SOFTWARE,

	// Speed menu (1600-1699)
	ID_SPEED_TOGGLE_PAUSE = 1600,
	ID_SPEED_TOGGLE_TURBO,
	ID_SPEED_TOGGLE_SLOW,
	ID_SPEED_TOGGLE_MUTE,
	ID_SPEED_50 = 1610,
	ID_SPEED_100,
	ID_SPEED_200,
	ID_SPEED_400,

	// Debug menu (1700-1799)
	ID_DEBUG_RUN_STOP = 1700,
	ID_DEBUG_STEP_INTO,
	ID_DEBUG_STEP_OVER,
	ID_DEBUG_STEP_OUT,
	ID_DEBUG_TOGGLE_DEBUGGER,
	ID_DEBUG_TOGGLE_BREAK_AT_EXE,
	ID_DEBUG_TOGGLE_AUTO_RELOAD_ROMS,

	// Configure dialogs (1750-1799)
	ID_CONFIGURE_SYSTEM = 1750,
	ID_CONFIGURE_CPU,
	ID_CONFIGURE_BOOT,
	ID_CONFIGURE_KEYBOARD,
	ID_CONFIGURE_AUDIO,
	ID_CONFIGURE_VIDEO,

	// Tools / Manager dialogs (1800-1899)
	ID_TOOLS_OPEN_CONFIG_DIR = 1800,
	ID_TOOLS_OPEN_FIRMWARE_DIR,
	ID_TOOLS_FIRMWARE_MANAGER,
	ID_TOOLS_DEVICE_MANAGER,
	ID_TOOLS_CARTRIDGE_BROWSER,
	ID_TOOLS_CASSETTE_CONTROL,
	ID_TOOLS_DISK_EXPLORER,
	ID_TOOLS_PROFILE_MANAGER,
	ID_TOOLS_CHEAT_ENGINE,
	ID_TOOLS_COMPAT_BROWSER,
	ID_TOOLS_RECORD_VIDEO,
	ID_TOOLS_STOP_RECORDING,

	// Help menu (1900-1999)
	ID_HELP_KEYBOARD_SHORTCUTS = 1900,
	ID_HELP_CHANGELOG,
	ID_HELP_ABOUT,

	// Internal (2000+)
	ID_GAMEPAD_TIMER_ID = 2000,
};
