# EmbedResources.cmake - Embed binary resource files into C++ source at configure time
#
# Usage:
#   embed_resources(
#     OUTPUT_FILE <path>          # Generated .cpp file path
#     RESOURCE_DIR <dir>          # Directory containing resource files
#     STUFF <id> <filename> ...   # STUFF resources (raw binary, loaded via ATLoadMiscResource)
#     PNG <id> <filename> ...     # PNG resources (images, loaded via ATLoadImageResource)
#   )

function(embed_resources)
    cmake_parse_arguments(ER "" "OUTPUT_FILE;RESOURCE_DIR" "STUFF;PNG" ${ARGN})

    if(NOT ER_OUTPUT_FILE)
        message(FATAL_ERROR "embed_resources: OUTPUT_FILE required")
    endif()
    if(NOT ER_RESOURCE_DIR)
        message(FATAL_ERROR "embed_resources: RESOURCE_DIR required")
    endif()

    # Start generating the C++ source
    set(CPP_CONTENT "// Auto-generated by EmbedResources.cmake — do not edit\n")
    string(APPEND CPP_CONTENT "#include <vd2/system/vdtypes.h>\n")
    string(APPEND CPP_CONTENT "#include <vd2/system/vdstl.h>\n")
    string(APPEND CPP_CONTENT "#include <cstring>\n\n")

    # Collect all resource entries for lookup tables
    set(STUFF_ENTRIES "")
    set(PNG_ENTRIES "")

    # Process STUFF resources (id filename pairs)
    list(LENGTH ER_STUFF stuff_count)
    math(EXPR stuff_pairs "${stuff_count} / 2")
    set(idx 0)
    while(idx LESS stuff_count)
        list(GET ER_STUFF ${idx} res_id)
        math(EXPR idx "${idx} + 1")
        list(GET ER_STUFF ${idx} res_file)
        math(EXPR idx "${idx} + 1")

        set(res_path "${ER_RESOURCE_DIR}/${res_file}")
        if(NOT EXISTS "${res_path}")
            message(WARNING "embed_resources: STUFF file not found: ${res_path}")
            continue()
        endif()

        file(READ "${res_path}" hex_content HEX)
        string(LENGTH "${hex_content}" hex_len)
        math(EXPR byte_count "${hex_len} / 2")

        # Convert hex pairs to 0xNN, format
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex_array "${hex_content}")
        # Insert newlines every 16 bytes (48 chars = 16 * "0xNN,")
        set(formatted "")
        string(LENGTH "${hex_array}" arr_len)
        set(pos 0)
        while(pos LESS arr_len)
            math(EXPR remaining "${arr_len} - ${pos}")
            if(remaining GREATER 80)
                set(chunk_len 80)
            else()
                set(chunk_len ${remaining})
            endif()
            string(SUBSTRING "${hex_array}" ${pos} ${chunk_len} chunk)
            string(APPEND formatted "\t${chunk}\n")
            math(EXPR pos "${pos} + ${chunk_len}")
        endwhile()

        # Clean variable name from ID
        string(APPEND CPP_CONTENT "static const uint8_t g_stuff_${res_id}[] = {\n${formatted}};\n\n")
        list(APPEND STUFF_ENTRIES "${res_id}")
    endwhile()

    # Process PNG resources (id filename pairs)
    list(LENGTH ER_PNG png_count)
    set(idx 0)
    while(idx LESS png_count)
        list(GET ER_PNG ${idx} res_id)
        math(EXPR idx "${idx} + 1")
        list(GET ER_PNG ${idx} res_file)
        math(EXPR idx "${idx} + 1")

        set(res_path "${ER_RESOURCE_DIR}/${res_file}")
        if(NOT EXISTS "${res_path}")
            message(WARNING "embed_resources: PNG file not found: ${res_path}")
            continue()
        endif()

        file(READ "${res_path}" hex_content HEX)
        string(LENGTH "${hex_content}" hex_len)
        math(EXPR byte_count "${hex_len} / 2")

        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex_array "${hex_content}")
        set(formatted "")
        string(LENGTH "${hex_array}" arr_len)
        set(pos 0)
        while(pos LESS arr_len)
            math(EXPR remaining "${arr_len} - ${pos}")
            if(remaining GREATER 80)
                set(chunk_len 80)
            else()
                set(chunk_len ${remaining})
            endif()
            string(SUBSTRING "${hex_array}" ${pos} ${chunk_len} chunk)
            string(APPEND formatted "\t${chunk}\n")
            math(EXPR pos "${pos} + ${chunk_len}")
        endwhile()

        string(APPEND CPP_CONTENT "static const uint8_t g_png_${res_id}[] = {\n${formatted}};\n\n")
        list(APPEND PNG_ENTRIES "${res_id}")
    endwhile()

    # Generate STUFF lookup table
    string(APPEND CPP_CONTENT "struct EmbeddedResource {\n\tconst uint8_t *data;\n\tsize_t size;\n};\n\n")

    string(APPEND CPP_CONTENT "static const struct { int id; EmbeddedResource res; } g_stuffTable[] = {\n")
    foreach(entry ${STUFF_ENTRIES})
        string(APPEND CPP_CONTENT "\t{ ${entry}, { g_stuff_${entry}, sizeof(g_stuff_${entry}) } },\n")
    endforeach()
    string(APPEND CPP_CONTENT "};\n\n")

    # Generate PNG lookup table
    string(APPEND CPP_CONTENT "static const struct { uint32 id; EmbeddedResource res; } g_pngTable[] = {\n")
    foreach(entry ${PNG_ENTRIES})
        string(APPEND CPP_CONTENT "\t{ ${entry}, { g_png_${entry}, sizeof(g_png_${entry}) } },\n")
    endforeach()
    string(APPEND CPP_CONTENT "};\n\n")

    # Generate lookup functions
    string(APPEND CPP_CONTENT "bool ATEmbeddedLoadMiscResource(int id, vdfastvector<uint8>& data) {\n")
    string(APPEND CPP_CONTENT "\tfor (const auto& e : g_stuffTable) {\n")
    string(APPEND CPP_CONTENT "\t\tif (e.id == id) {\n")
    string(APPEND CPP_CONTENT "\t\t\tdata.resize(e.res.size);\n")
    string(APPEND CPP_CONTENT "\t\t\tmemcpy(data.data(), e.res.data, e.res.size);\n")
    string(APPEND CPP_CONTENT "\t\t\treturn true;\n")
    string(APPEND CPP_CONTENT "\t\t}\n")
    string(APPEND CPP_CONTENT "\t}\n")
    string(APPEND CPP_CONTENT "\treturn false;\n")
    string(APPEND CPP_CONTENT "}\n\n")

    string(APPEND CPP_CONTENT "bool ATEmbeddedLoadImageResource(uint32 id, const void *& pData, size_t& size) {\n")
    string(APPEND CPP_CONTENT "\tfor (const auto& e : g_pngTable) {\n")
    string(APPEND CPP_CONTENT "\t\tif (e.id == id) {\n")
    string(APPEND CPP_CONTENT "\t\t\tpData = e.res.data;\n")
    string(APPEND CPP_CONTENT "\t\t\tsize = e.res.size;\n")
    string(APPEND CPP_CONTENT "\t\t\treturn true;\n")
    string(APPEND CPP_CONTENT "\t\t}\n")
    string(APPEND CPP_CONTENT "\t}\n")
    string(APPEND CPP_CONTENT "\treturn false;\n")
    string(APPEND CPP_CONTENT "}\n")

    file(WRITE "${ER_OUTPUT_FILE}" "${CPP_CONTENT}")
    list(LENGTH PNG_ENTRIES png_entry_count)
    list(LENGTH STUFF_ENTRIES stuff_entry_count)
    message(STATUS "Generated embedded resources: ${stuff_entry_count} STUFF + ${png_entry_count} PNG entries -> ${ER_OUTPUT_FILE}")
endfunction()
